### ISSUE TITLE
acsip-s76g board support

### ISSUE THREAD

**Issue by cairo-caplan** [CoXlabInc/nola-sdk#1]
Hello, I would like to know how I can install the support for the "acsip-s76g" board, as used in the example https://github.com/CoXlabInc/Nol.A-AcSip-S76G-Example .

**Comment by jsjeong** [comment]
As I mentioned at https://github.com/CoXlabInc/Nol.A-AcSip-S76G-Example/issues/1, it is not supported currently.

**Comment by cairo-caplan** [comment]
Thank you for the feedback
